csv:
  value: 'data_Normalized.csv'
n_class:
  value: 1
batch_size:
  value: 2
epochs:
  value: 50
learning_rate:
  value: 1e-4
optimizer:
  value: torch.optim.Adam
encoder_model:
  value: 'resnet18'
patch_size:
  value: (512, 512)
aug_prob:
  value: 0.5
lambda_consistency:
  value: 1.0
ema_decay:
  value: 0.99
