program: 3_experiments.py
method: grid
name: sweep_gland_seg
metric:
  name: val_dice
  goal: maximize
parameters:
  epochs:
    values: [20, 30,50]
  learning_rate:
    values: [0.00005, 0.0001, 0.0005, 0.001, 0.002]
  optimizer:
    values: ["torch.optim.Adam"]
  encoder_model:
    values: ["resnet18"]
  n_class:
    values: [1]
  patchsize:
    values: [256, 512]
  batchsize:
    values: [8,16,32,48]
  augmentation_prob:
    values: [0.3, 0.5, 0.7]
